### ISSUE TITLE
openwrt iptables needed

### ISSUE THREAD

**Issue by hieixu** [ym/shanghai-telecom-go-to-hell#1]
I just use following code in openwrt router, It seems work well. Where 192.168.10.244 is my lan server. 

iptables -t nat -A PREROUTING -d 58.215.179.159 -j DNAT --to-destination 192.168.10.244
iptables -t nat -A PREROUTING -d 116.252.178.229 -j DNAT --to-destination 192.168.10.244

**Comment by ym** [comment]
Added :-)
